import React, { createContext, useContext, useState, useEffect } from 'react';
import { translations } from '../data/translations';
import { API_BASE } from '../config/api';

const AppContext = createContext();

const defaultSensors = () => ({
  n: 45, p: 32, k: 58,
  moisture: 42.5,
  ph: 6.8,
  temp: 24.5,
  humidity: 62,
  rainfall: 1200,
});

export const AppProvider = ({ children, dataMode = 'simulation', authToken = null, liveProfile = null }) => {
  const [language, setLanguage] = useState('en');
  const [sensorData, setSensorData] = useState(defaultSensors);
  const [alerts, setAlerts] = useState(() => dataMode === 'live' ? [] : [
    { id: 1, type: 'warning', message: 'anomaly_moisture' },
    { id: 2, type: 'info', message: 'anomaly_temp' }
  ]);
  const [recommendation, setRecommendation] = useState(null);

  const t = (key) => translations[language][key] || key;

  useEffect(() => {
    if (dataMode === 'live') {
      if (liveProfile?.sensors) {
        const s = liveProfile.sensors;
        setSensorData({
          n: s.n,
          p: s.p,
          k: s.k,
          moisture: s.moisture,
          ph: s.ph,
          temp: s.temp,
          humidity: s.humidity,
          rainfall: s.rainfall,
        });
        setAlerts([]);
      } else {
        setSensorData({
          n: 0, p: 0, k: 0, moisture: 0, ph: 0, temp: 0, humidity: 0, rainfall: 0
        });
        setAlerts([]);
      }
    } else {
      setSensorData(defaultSensors());
      setAlerts([
        { id: 1, type: 'warning', message: 'anomaly_moisture' },
        { id: 2, type: 'info', message: 'anomaly_temp' }
      ]);
    }
  }, [dataMode, liveProfile]);

  useEffect(() => {
    if (dataMode !== 'simulation') return undefined;
    const interval = setInterval(() => {
      setSensorData(prev => ({
        ...prev,
        moisture: Math.max(0, Math.min(100, prev.moisture + (Math.random() - 0.5) * 2)),
        temp: prev.temp + (Math.random() - 0.5) * 0.5,
        humidity: Math.max(0, Math.min(100, prev.humidity + (Math.random() - 0.5) * 2))
      }));
    }, 5000);
    return () => clearInterval(interval);
  }, [dataMode]);

  const randomBetween = (min, max, decimals) => {
    const str = (Math.random() * (max - min) + min).toFixed(decimals);
    return parseFloat(str);
  };

  const randomizeSensors = () => {
    if (dataMode === 'live') {
      console.warn('Randomization disabled during LIVE session.');
      return;
    }
    setSensorData({
      n: randomBetween(20, 159, 1),
      p: randomBetween(10, 89, 1),
      k: randomBetween(10, 119, 1),
      ph: randomBetween(4.5, 8.5, 1),
      moisture: randomBetween(10, 85, 1),
      temp: randomBetween(10, 45, 1),
      humidity: randomBetween(20, 95, 1),
      rainfall: randomBetween(500, 3000, 1),
    });
  };

  const saveRecord = (format = 'json') => {
    if (!recommendation) return;
    
    if (format === 'text') {
      const reportContent = `
=========================================
KISAN-SETU: FIELD INTELLIGENCE REPORT
=========================================
Timestamp: ${new Date().toLocaleString()}

01 FIELD IDENTIFICATION
-----------------------------------------
Crop Type: ${recommendation.farmInfo.cropType.replace('crop_', '').toUpperCase()}
Growth Stage: ${recommendation.farmInfo.growthStage.replace('stage_', '').toUpperCase()}
Soil Type: ${recommendation.farmInfo.soilType.replace('soil_', '').toUpperCase()}
Irrigation: Standard Ground Access

02 FIELD TELEMETRY DATA
-----------------------------------------
Nitrogen (N): ${recommendation.sensorDetails.n} mg/kg [${recommendation.nStatus}]
Phosphorus (P): ${recommendation.sensorDetails.p} mg/kg [${recommendation.pStatus}]
Potassium (K): ${recommendation.sensorDetails.k} mg/kg [${recommendation.kStatus}]
Soil pH: ${recommendation.sensorDetails.ph} [${recommendation.phStatus}]
Moisture: ${recommendation.sensorDetails.moisture}%
Temperature: ${recommendation.sensorDetails.temp}°C
Humidity: ${recommendation.sensorDetails.humidity}%
Rainfall: ${recommendation.sensorDetails.rainfall} mm
 

03 AI SYNTHESIS RECOMMENDATION
-----------------------------------------
TARGET FERTILIZER: ${recommendation.fertilizer.toUpperCase()}
RECOMMENDED DOSAGE: ${recommendation.dosage}

ADVISORY PROTOCOL:
"${recommendation.advisory}"

-----------------------------------------
Generated by Kisan-Setu AI Synthesis Engine
=========================================`;

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `kisan_setu_report_${Date.now()}.txt`;
      a.click();
      alert('Field report generated successfully as a Text File (.txt).');
      return;
    }

    const record = {
      timestamp: new Date().toISOString(),
      recommendation
    };
    const blob = new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kisan_setu_record_${Date.now()}.json`;
    a.click();
    alert(`JSON record saved successfully!`);
  };

  const getRecommendation = async (farmData) => {
    if (!farmData.cropType || !farmData.growthStage || !farmData.soilType) {
      alert('Please select Crop Type, Growth Stage, and Soil Type before generating synthesis.');
      return 'validation_error';
    }

    const cropMap = { 
      'crop_wheat': 'Wheat', 'crop_rice': 'Rice', 'crop_maize': 'Maize', 
      'crop_cotton': 'Cotton', 'crop_potato': 'Potato', 'crop_sugarcane': 'Sugarcane', 
      'crop_tomato': 'Tomato' 
    };
    const soilMap = { 
      'soil_clay': 'Clay', 'soil_sandy': 'Sandy', 'soil_loamy': 'Loamy', 'soil_silt': 'Silt' 
    };
    const stageMap = { 
      'stage_sowing': 'Sowing', 'stage_vegetative': 'Vegetative', 
      'stage_flowering': 'Flowering', 'stage_harvest': 'Harvest' 
    };

    try {
      const response = await fetch(`${API_BASE}/predict`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Data-Mode': dataMode,
          ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
        },
        body: JSON.stringify({
          soil_type: soilMap[farmData.soilType],
          soil_ph: sensorData.ph,
          soil_moisture: sensorData.moisture,
          nitrogen: sensorData.n,
          phosphorus: sensorData.p,
          potassium: sensorData.k,
          temperature: sensorData.temp,
          humidity: sensorData.humidity,
          rainfall: sensorData.rainfall,
          crop_type: cropMap[farmData.cropType],
          growth_stage: stageMap[farmData.growthStage],
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || 'Backend synthesis failed');
      }
      const data = await response.json();

      setRecommendation({
        farmInfo: farmData,
        fertilizer: `${data.predicted_fertilizer}`,
        dosage: `${data.recommended_dosage}`,
        advisory: data.advisory,
        phStatus: data.ph_status.toUpperCase(),
        phValue: sensorData.ph,
        nStatus: data.nitrogen_status.toUpperCase(),
        pStatus: data.phosphorus_status.toUpperCase(),
        kStatus: data.potassium_status.toUpperCase(),
        sensorDetails: { ...sensorData }
      });
    } catch (error) {
      console.error('Error fetching recommendation:', error);
      setRecommendation({
        error: true,
        message: error.message || 'System Error: Backend unreachable',
        fertilizer: 'Analysis Suspended',
        dosage: 'Check Connectivity',
        advisory: 'Ensure sensors are providing non-zero values in the database for the active profile.',
      });
    }
  };

  const value = {
    language, setLanguage,
    sensorData, setSensorData,
    alerts, setAlerts,
    recommendation, setRecommendation,
    getRecommendation,
    randomizeSensors,
    saveRecord,
    t
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};

export const useApp = () => useContext(AppContext);
